
export const fileToBase64 = (file: File): Promise<string> => {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.readAsDataURL(file);
    reader.onload = () => {
      // Result is "data:image/jpeg;base64,...."
      // We only want the part after the comma
      const result = reader.result as string;
      resolve(result.split(',')[1]);
    };
    reader.onerror = (error) => reject(error);
  });
};

export const addWatermark = (base64ImgDataUrl: string): Promise<string> => {
  return new Promise((resolve, reject) => {
    const canvas = document.createElement('canvas');
    const ctx = canvas.getContext('2d');
    if (!ctx) {
      return reject(new Error('Could not get canvas context'));
    }

    const img = new Image();
    img.crossOrigin = 'anonymous';
    img.src = base64ImgDataUrl;

    img.onload = () => {
      canvas.width = img.width;
      canvas.height = img.height;
      ctx.drawImage(img, 0, 0);

      ctx.globalAlpha = 0.7;
      const fontSize = Math.max(16, Math.floor(canvas.width / 30));
      ctx.font = `600 ${fontSize}px Poppins`;
      ctx.fillStyle = 'white';
      ctx.textAlign = 'center';
      
      const text = 'Generated by Trendify AI';
      const textMetrics = ctx.measureText(text);
      const textHeight = textMetrics.actualBoundingBoxAscent + textMetrics.actualBoundingBoxDescent;
      const padding = Math.max(20, canvas.height * 0.03);

      // Add a subtle shadow for better readability
      ctx.shadowColor = 'rgba(0, 0, 0, 0.7)';
      ctx.shadowBlur = 5;
      ctx.shadowOffsetX = 2;
      ctx.shadowOffsetY = 2;

      ctx.fillText(text, canvas.width / 2, canvas.height - padding);
      
      resolve(canvas.toDataURL('image/jpeg', 0.9));
    };

    img.onerror = (error) => {
      reject(error);
    };
  });
};
